export const ROUTES = {
  welcome:            '/welcome',
  login:               '/login',
  oauthCallback:        '/oauth/callback',
  privacy:              '/privacy',
  terms:                '/terms',
  mentions:             '/mentions',
  licenses:             '/licenses',
  setupSync:            '/setup-sync',
  pinUnlock:            '/pin-unlock',
  recoveryUnlock:       '/recovery-unlock',
  migrateSync:          '/migrate-sync',

  messages:             '/messages',
  message:  (id: string) => `/messages/${id}`,
  contacts:             '/contacts',
  more:                 '/more',
  settings:             '/settings',
  settingsAppearance:   '/settings/appearance',
  settingsLanguage:     '/settings/language',
  settingsSync:         '/settings/sync',
  security:             '/security',
  devices:              '/devices',
  about:                '/about',
} as const;
